language: node_js
node_js:
  - "11"
branches:
  only:
  - master
  - develop
  - /^release-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
script:
  - npm run test
  - npm run test:integration
  - npm run build
