dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "9"
before_install:
  - node --version
install:
  - npm install
script:
  - npm run test
  - npm run test:integration
